name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Dependencies install
        run: npm i
        
      - name: Build
        run: npm run build
        
      - name: Server | Copy App
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: >
            .,
            !node_modules,
            !src,
            !.vscode,
            !.git,
            !.gitignore,
            !.github,
            !.editorconfig,
            !.eslintignore,
            !.eslintrc.json,
            !.dockerignore,
            !babel.config.js,
            !jest.config.ts,
            !tsconfig.json,
            !diagram.png
          target: "~/app"
          
      - name: Server | Dependencies | Migrations | Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app
            npm install
            npm run typeorm migration:run 
            pm2 restart rentx_api
